### ISSUE TITLE
Copies of identical files lead to problems

### ISSUE THREAD

**Issue by Atelaes** [Atelaes/Mynda#59]
If two copies of an identical file (with an identical hash) are found, it starts a bizarre replication bug.  Mynda should probably catch this when adding things to library, alert the user, and let them pick one.

https://photos.google.com/share/AF1QipNTGeqIasTYyNS7V143JOIWJcLe2f_nVNem9fi9qHmXyGi7wRAXzfoh2iYgOs0EVQ/photo/AF1QipNrSqK5GFrFQZDes9t_iDQqoxlyY9oCdtIsRlPq?key=c0FQenhxUndUOW1mX3dJV2NqM0NWUjFRNG9NVFhB

**Comment by JohnMTorgerson** [comment]
Mynda now just doesn't add duplicate movies.
