### ISSUE TITLE
Column Width Problem

### ISSUE THREAD

**Issue by Atelaes** [Atelaes/Mynda#63]
Director Column seems to expand to fit, so one movie with seven directors (like Animatrix) causes it to balloon and knock off all other columns.  Draggable resizing is something we should do eventually, but for now a fixed sensible width with ellipsis for overflow is at least usable.

**Comment by JohnMTorgerson** [comment]
Put a maximum width of 15ems on every td. We just need to add MynOverflowTextMarquee where appropriate. And eventually, we should make the columns resizeable.
